#!/bin/sh

# Xcode Cloud post-clone step.
#
# Barry's Xcode project (ios/Barry.xcodeproj) is generated by XcodeGen and is
# intentionally .gitignored, so it is NOT in the repository Xcode Cloud clones.
# Regenerate it here — before Xcode Cloud resolves and builds the scheme — so the
# "Project Barry.xcodeproj does not exist" failure can't happen.

set -e

export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

echo "→ Installing XcodeGen"
brew install xcodegen

echo "→ Generating Barry.xcodeproj"
cd "$CI_PRIMARY_REPOSITORY_PATH/ios"
xcodegen generate

echo "✓ Project generated"
